# Generated by Django 3.1.7 on 2024-04-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRUDAppStudentTable',
            new_name='CRUDApp_StudentTable',
        ),
    ]
